steps:
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['test']
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['package','-Dmaven.test.skip=true']
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','europe-docker.pkg.dev/$PROJECT_ID/gcb-study/javasample:$TAG_NAME','--build-arg=JAR_FILE=target/sample-0.0.1-SNAPSHOT.jar','.']
- name: gcr.io/cloud-builders/docker
  args: ['push','europe-docker.pkg.dev/$PROJECT_ID/gcb-study/javasample:$TAG_NAME']
- name: gcr.io/cloud-builders/gke-deploy
  args:
  - run
  - --filename=kubernetes/javasample.yaml
  - --image=europe-docker.pkg.dev/$PROJECT_ID/gcb-study/javasample:$TAG_NAME
  - --cluster=devcluster
  - --location=europe-west1-b

